import {
  PUBLIC_GOOGLE_CALENDAR_API_KEY,
  PUBLIC_GOOGLE_CALENDAR_EVENTS,
  PUBLIC_GOOGLE_CALENDAR_LAN,
  PUBLIC_GOOGLE_CALENDAR_CONVENTIONS,
  PUBLIC_GOOGLE_CALENDAR_TWITCH,
	PUBLIC_GOOGLE_SHEET_API_KEY,
	PUBLIC_GOOGLE_SHEET_LAN_SOLO,
	PUBLIC_GOOGLE_SHEET_LAN_MULTI,
} from "$env/static/public";

export const GoogleCalendarConfig = {
  API_KEY: PUBLIC_GOOGLE_CALENDAR_API_KEY ?? "UNDEFINED",
  CALENDARS: {
    EVENTS: PUBLIC_GOOGLE_CALENDAR_EVENTS ?? null,
    LAN: PUBLIC_GOOGLE_CALENDAR_LAN ?? null,
    CONVENTIONS: PUBLIC_GOOGLE_CALENDAR_CONVENTIONS ?? null,
    TWITCH: PUBLIC_GOOGLE_CALENDAR_TWITCH ?? null,
  },
};

export const GoogleSheetConfig = {
  API_KEY: PUBLIC_GOOGLE_SHEET_API_KEY ?? "UNDEFINED",
  BOARDS: {
  	SOLO: PUBLIC_GOOGLE_SHEET_LAN_SOLO ?? "",
  	MULTI: PUBLIC_GOOGLE_SHEET_LAN_MULTI ?? "",
  },
}